package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// mockTransport stands in for real network access to the AI providers,
// Google APIs, and misc third-party endpoints this workflow calls. It
// never touches the network. Responses are shaped to match exactly what
// the workflow's own downstream Code nodes parse (verified by reading
// Parse JSON / Apply Fact Check Fixes / Apply Generated Image Prompts /
// Merge Semantic Result / Parse QC Result), so a "success" run below
// exercises the REAL parsing logic, not just each node's fallback path.
type mockTransport struct {
	log []string
}

func geminiWrap(payload any) []byte {
	b, _ := json.Marshal(payload)
	body := map[string]any{
		"candidates": []any{
			map[string]any{
				"content": map[string]any{
					"parts": []any{map[string]any{"text": string(b)}},
				},
			},
		},
	}
	out, _ := json.Marshal(body)
	return out
}

var validScript = map[string]any{
	"title":         "5 Deep Ocean Signals Scientists Still Cannot Explain",
	"topic":         "deep ocean mysteries synthetic test topic",
	"hook":          "What is making that sound two miles under the Pacific?",
	"description":   "A synthetic test script generated by the e2echeck harness, not a real AI response.",
	"tags":          []string{"ocean", "science", "mystery", "shorts"},
	"pinnedComment": "Which one surprised you most?",
	"scenes": []map[string]any{
		{"scene": 1, "voice": "What is making that sound two miles under the Pacific?", "image_prompt": "cinematic vertical 9:16 deep ocean glow photorealistic"},
		{"scene": 2, "voice": "Scientists recorded it five times and still cannot explain it.", "image_prompt": "cinematic vertical 9:16 sonar array dramatic lighting"},
		{"scene": 3, "voice": "The frequency matches nothing in the known animal kingdom.", "image_prompt": "cinematic vertical 9:16 abyssal trench photorealistic"},
		{"scene": 4, "voice": "One theory says it is geological, not biological at all.", "image_prompt": "cinematic vertical 9:16 tectonic vent glowing dramatic"},
		{"scene": 5, "voice": "Until it happens again, the ocean keeps the answer to itself.", "image_prompt": "cinematic vertical 9:16 dark ocean horizon cinematic"},
	},
}

func (t *mockTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	var bodyBytes []byte
	if req.Body != nil {
		bodyBytes, _ = io.ReadAll(req.Body)
		req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
	}
	bodyStr := string(bodyBytes)
	url := req.URL.String()
	t.log = append(t.log, fmt.Sprintf("%s %s (body %dB)", req.Method, url, len(bodyBytes)))

	resp := func(status int, ctype string, body []byte) *http.Response {
		return &http.Response{
			StatusCode: status,
			Status:     fmt.Sprintf("%d", status),
			Body:       io.NopCloser(bytes.NewReader(body)),
			Header:     http.Header{"Content-Type": []string{ctype}},
			Request:    req,
		}
	}

	switch {
	case strings.Contains(url, "openrouter.ai/api/v1/models"):
		return resp(200, "application/json", []byte(`{"data":[
			{"id":"meta-llama/llama-3.3-70b-instruct:free","name":"Llama 3.3 70B (free)",
			 "pricing":{"prompt":"0","completion":"0","request":"0","image":"0"},
			 "architecture":{"modality":"text->text"}}
		]}`)), nil

	case strings.Contains(url, "generativelanguage.googleapis.com") || strings.Contains(url, "openrouter.ai/api/v1/chat/completions"):
		var payload any
		switch {
		case strings.Contains(bodyStr, "world-class viral YouTube Shorts scriptwriter"):
			payload = validScript
		case strings.Contains(bodyStr, "fact-checker for a short YouTube Shorts script"):
			payload = validScript // same shape: title/topic/description/tags/scenes
		case strings.Contains(bodyStr, "professional visual director for viral YouTube Shorts"):
			payload = map[string]any{"image_prompts": []string{
				"cinematic vertical 9:16 deep ocean glow photorealistic v2",
				"cinematic vertical 9:16 sonar array dramatic lighting v2",
				"cinematic vertical 9:16 abyssal trench photorealistic v2",
				"cinematic vertical 9:16 tectonic vent glowing dramatic v2",
				"cinematic vertical 9:16 dark ocean horizon cinematic v2",
			}}
		case strings.Contains(bodyStr, "expert semantic duplicate-content auditor"):
			payload = map[string]any{"duplicate": false, "reason": "distinct topic", "matched": ""}
		case strings.Contains(bodyStr, "strict, professional YouTube Shorts video QC reviewer"):
			payload = map[string]any{
				"visual_quality":             map[string]any{"score": 7.5, "feedback": "Solid contrast, minor framing drift between scenes."},
				"editing":                    map[string]any{"score": 7, "feedback": "Pacing is reasonable but transitions feel abrupt."},
				"subtitles":                  map[string]any{"score": 8, "feedback": "Readable and well-timed."},
				"transitions":                map[string]any{"score": 6.5, "feedback": "Scene 3 to 4 cut is jarring."},
				"viewer_retention_potential": map[string]any{"score": 7, "feedback": "Hook is decent but not exceptional."},
				"overall":                    map[string]any{"score": 7.2, "feedback": "Improve scene 3-4 transition smoothness first."},
			}
		default:
			payload = validScript
		}
		return resp(200, "application/json", geminiWrap(payload)), nil

	case strings.Contains(url, "api.languagetool.org"):
		return resp(200, "application/json", []byte(`{"matches":[]}`)), nil

	case strings.Contains(url, "trends.google.com"):
		return resp(200, "application/rss+xml", []byte(`<?xml version="1.0"?><rss version="2.0"><channel><title>Trends</title></channel></rss>`)), nil

	case strings.Contains(url, "en.wikipedia.org"):
		return resp(200, "application/json", []byte(`{"query":{"random":[{"id":1,"ns":0,"title":"Synthetic Test Topic"}]}}`)), nil

	case strings.Contains(url, "image.pollinations.ai"):
		// Minimal valid JPEG (SOI+EOI markers) so any downstream magic-byte check passes.
		return resp(200, "image/jpeg", []byte{0xFF, 0xD8, 0xFF, 0xD9}), nil

	case strings.Contains(url, "googleapis.com/youtube/v3/videos"):
		return resp(200, "application/json", []byte(`{"items":[{"id":"synthTrend1","snippet":{"title":"Synthetic trending video"},"statistics":{"viewCount":"1000"}}]}`)), nil

	case strings.Contains(url, "googleapis.com/upload/youtube/v3/videos"):
		return resp(200, "application/json", []byte(`{"id":"synthUploadedVideoId","status":{"uploadStatus":"uploaded"}}`)), nil

	case strings.Contains(url, "googleapis.com/upload/youtube/v3/thumbnails"):
		return resp(200, "application/json", []byte(`{}`)), nil

	case strings.Contains(url, "googleapis.com/youtube/v3/commentThreads"):
		return resp(200, "application/json", []byte(`{"id":"synthCommentId"}`)), nil

	case strings.Contains(url, "sheets.googleapis.com"):
		if strings.Contains(url, "UsedTopics") {
			return resp(200, "application/json", []byte(`{"values":[
				["title","topic","hook","description","tags","entities"],
				["3 Cold War Secrets Nobody Talks About","cold war secret operations","What really happened at that base?","A synthetic prior-run row for e2echeck testing.","coldwar,history,shorts","Area 51,U-2"]
			]}`)), nil
		}
		return resp(200, "application/json", []byte(`{"values":[["title","topic","hook","description","tags","entities"]]}`)), nil

	case strings.Contains(url, "gmail.googleapis.com"):
		return resp(200, "application/json", []byte(`{"id":"synthMsgId"}`)), nil

	case url == "":
		return nil, fmt.Errorf("mockTransport: empty URL (unresolved expression)")

	default:
		// Generic webhook/notification endpoints (NOTIFY_WEBHOOK_URL etc.)
		return resp(200, "text/plain", []byte("OK")), nil
	}
}
