const {JSDOM}=require("jsdom");const fs=require("fs");
const root="/home/claude/microflow/MICROFLOW-main/cmd/server/static/";
const html=fs.readFileSync(root+"index.html","utf8").replace(/<script src="\/app.js"><\/script>/,"");
const calls=[];
const services=[{id:"default",name:"Default"},{id:"s2-abc",name:"Shorts 2"}];
const dom=new JSDOM(html,{url:"http://localhost/#/dashboard",runScripts:"outside-only",pretendToBeVisual:true});
const w=dom.window;
w.fetch=async(path,opts)=>{opts=opts||{};calls.push({path,h:(opts.headers||{})["X-Microflow-Service"],m:opts.method||"GET"});
 const j=(b)=>({ok:true,status:200,json:async()=>b});
 if(path==="/api/services")return j(services);
 if(/^\/api\/services\/[^/]+$/.test(path))return j({id:"x",name:"x",workflowCount:2});
 if(path.startsWith("/api/workflows"))return j([{id:"w1",name:"WF",active:true,nodes:{a:{}}}]);
 if(path==="/api/run-all")return j({status:"idle",results:[]});
 if(path.endsWith("/env")||path==="/api/global-env")return j([{key:"K",isSecret:true,updatedAt:new Date().toISOString()}]);
 if(path.startsWith("/api/executions"))return j({executions:[{id:"e1",workflowId:"w1",status:"success"},{id:"e2",workflowId:"OTHER",status:"success"}],queue:{}});
 return j({});};
w.eval(fs.readFileSync(root+"app.js","utf8"));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 await sleep(200);
 const d=w.document;let fail=0;const ok=(c,m)=>{console.log((c?"PASS ":"FAIL ")+m);if(!c)fail++;};
 ok(d.getElementById("serviceSwitch").options.length===2,"switcher populated");
 ok(/Run Service/.test(d.getElementById("view").innerHTML),"dashboard has Run Service");
 ok(/Run All Services/.test(d.getElementById("view").innerHTML),"dashboard has Run All");
 ok(calls.some(c=>c.path.startsWith("/api/workflows?serviceId=default")&&c.h==="default"),"workflows scoped + header");
 w.location.hash="#/services";await sleep(200);
 ok(/Create Service/.test(d.getElementById("view").innerHTML)&&/Shorts 2/.test(d.getElementById("view").innerHTML),"services page");
 w.location.hash="#/global-env";await sleep(150);
 ok(/Global Environment/.test(d.getElementById("view").innerHTML)&&/<code>K<\/code>/.test(d.getElementById("view").innerHTML),"global env page");
 d.getElementById("serviceSwitch").value="s2-abc";d.getElementById("serviceSwitch").dispatchEvent(new w.Event("change"));
 w.location.hash="#/service-env";await sleep(150);
 ok(calls.some(c=>c.path==="/api/services/s2-abc/env"&&c.h==="s2-abc"),"service env scoped to selected service");
 w.location.hash="#/executions";await sleep(250);
 ok(!/e2/.test(d.getElementById("view").innerHTML),"other service's execution filtered out");
 w.location.hash="#/services/s2-abc/credentials?googleConnected=gmail";await sleep(200);
 ok(calls.some(c=>c.path==="/api/services/s2-abc/google/connections"),"OAuth callback route selects service & loads connections");
 console.log(fail?"FAILED "+fail:"ALL PASS");process.exit(fail?1:0);
})();
